### PR TITLE
Adds node modules as a volume

### LINKED ISSUE #754: Figure out optimal Dockerfile
Current setup uses a `volume` to transfer code over into the container

So when we run npm install on build, the modules get installed. But the volume then overrides the `node_modules` folder with nothing.

The temp solution for now is to run `npm install` locally.

Ideally we should not require this step.

### PR DESCRIPTION
**Pull request by deadlybutter**
#### What's this PR do?
Mounts a volume for node_modules, apparently its that easy!
http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
http://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds

#### How should this be reviewed?
Can you docker-compose up without running npm install?

#### Relevant tickets
Fixes #754

### CODE REVIEW

**Comment by deadlybutter** [comment]
Closing this in favor of Activity Events PR #756 ^

**Comment by deadlybutter** [comment]
[Add Node Modules as a volume in Dockerfile](https://trello.com/c/q7fGf7qP/3-add-node-modules-as-a-volume-in-dockerfile)

**Comment by aaronschachter** [comment]
@deadlybutter Not sure how to test this one... or maintain the Docker setup in general...

**Comment by deadlybutter** [comment]
@aaronschachter Me & sergii found a weird bug w/ Docker when it came to installing new npm modules, this was the fix. As I said during the meeting feel free to ignore Docker / remove it if you want! I think we were excited to play around with it but it's not being used on prod

**Comment by aaronschachter** [comment]
@deadlybutter Since there aren't any plans to start using Docker in production in the near future, I'm going to close this and #754 for now.

**Pull request closed without merging**
