### PR TITLE
Consolebot

### PR DESCRIPTION
**Pull request by aaronschachter**
#### What's this PR do?
Adds a `consolebot` script to testing post to the chatbot endpoint locally. 

#### How should this be reviewed?
Pull down this branch, start Gambit, and run `node shell` from another terminal window.

#### Any background context you want to provide?
This came in really handy for [testing Slothie](https://github.com/DoSomething/slothie/blob/master/consolebot.js) locally, thought it'd be sweet to add to the Gambie as we start adding Rivescript replies.

screen shot 2017-07-13 at 9 42 31 am

### CODE REVIEW

**Comment by aaronschachter** [comment]
@rapala61 I'm going to look into refactoring this a la [`lib/dashbot`](https://github.com/DoSomething/gambit/blob/4.5.6/lib/dashbot.js) and write some tests so we won't be decreasing coverage.

**Comment by rapala61** [comment]
@aaronschachter should I review now or after refactoring?

**Comment by aaronschachter** [comment]
@rapala61 -- I'll ping you when I've updated the PR. Do you think defining the Consolebot class in the `lib` makes sense? (`/lib/tools`?)

**Comment by rapala61** [comment]
@aaronschachter inside `libs/` makes sense, like `lib/dashbot.js`. I personally think the profiler stuff should be in `lib/profiler` and not in `lib/tools`, but it wasn't a priority so I haven't refactored that.

**Comment by aaronschachter** [comment]
@rapala61 This is ready for review whenever you have a chance.

**Comment by rapala61** [comment]
I see this in the console when running `npm test`, the tests pass, but I'm not sure if I'm missing something:
screen shot 2017-07-14 at 10 49 17 am

**Comment by aaronschachter** [comment]
Hm, yeah that `MaxListenersExceededWarning` is what's causing the Bot to respond with `'Internal Server Error'`. The warning says 11 end listeners were added: the `consolebot.test.js` calls `const consolebot = new Consolebot(config);` 10 times. 

I'm thinking this shouldn't matter much since we'd never run the shell script or tests on production -- and that's it cleaner to call `const consolebot = new Consolebot(config);` in each test (vs having one test with a few different spies). What do you think @rapala61? 
cc @sergii-tkachenko

**Comment by aaronschachter** [comment]
It could potentially make sense to not add this to the repo and instead in a separate... either in [odoyle-scripts](https://github.com/dosomething/odoyle-scripts) or a [Slothbot](https://github.com/dosomething/slothbot) add-on... , but it seemed to make sense so dev's wouldn't needed to keep the port number / api key in sync. However -- I've been seeing this error locally, even after the shell script is done running.  

internal/util.js:183
  throw new errors.Error('ERR_UNKNOWN_SIGNAL', signal);

```
09:34:31 web.1   |  info: Started worker 1
09:34:32 web.1   |  info: config.mongooseConnection.connection.readyState:1
09:34:32 web.1   |  info: Gambit is listening on port:5000 env:thor.
internal/util.js:183
  throw new errors.Error('ERR_UNKNOWN_SIGNAL', signal);
  ^

Error [ERR_UNKNOWN_SIGNAL]: Unknown signal: null
    at convertToValidSignal (internal/util.js:183:9)
    at ChildProcess.kill (internal/child_process.js:373:5)
    at EventEmitter.<anonymous> (/Users/aschachter/.local/share/heroku/client/node_modules/foreman/lib/proc.js:54:11)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
    at ChildProcess.<anonymous> (/Users/aschachter/.local/share/heroku/client/node_modules/foreman/lib/proc.js:50:13)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
```

**Comment by rapala61** [comment]
@aaronschachter What about if we add this `process.stdin.setMaxListeners(process.stdin.getMaxListeners() + 10);` inside a `test.before` block? It would increase the event limit for stdin just for testing.

**Comment by rapala61** [comment]
More on before and after hooks: https://github.com/avajs/ava#before--after-hooks

**Comment by aaronschachter** [comment]
Great idea! I've pushed a commit that bumps/resets it before/after each test. The `MaxListenersExceededWarning` is gone, but the `start` test is still triggering and `Internal Server Error` somehow (although technically the Bot's returning the error). The `node shell` script seems to run fine though, and I'm not seeing the `ERR_UNKNOWN_SIGNAL` anymore from the main server console...

**Comment by rapala61** [comment]
@aaronschachter  I feel I'm missing something about using the `node shell`. This is what I see in the logs for my local gambit:
```
1:12:30 PM web.1 |  info: Receiving: incoming input
1:12:30 PM web.1 |  info: /v1/chatbot post:{"incoming_message":"hi"}
1:12:30 PM web.1 |  debug: User.lookup(mobile, consolebot)
1:12:31 PM web.1 |  info: User.lookup could not find mobile:consolebot
1:12:31 PM web.1 |  debug: User.post
1:12:31 PM web.1 |  {"id":"5966b36510707d49445dba71","_id":"5966b36510707d49445dba71","first_name":null,"last_name":null,"last_initial":"","photo":null,"email":"consolebot@mobile.import","mobile":null,"facebook_id":null,"interests":null,"birthdate":null,"addr_street1":null,"addr_street2":null,"addr_city":null,"addr_state":null,"addr_zip":null,"source":"sms","source_detail":null,"slack_id":null,"mobilecommons_id":null,"parse_installation_ids":null,"mobilecommons_status":null,"language":null,"country":null,"drupal_id
1:12:31 PM web.1 |  >  ":"9310047","role":"user","last_accessed_at":null,"last_authenticated_at":null,"updated_at":"2017-07-14T17:12:34+00:00","created_at":"2017-07-12T23:40:21+00:00"}
1:12:31 PM web.1 |  info: northstar.Users created user:5966b36510707d49445dba71
1:12:31 PM web.1 |  debug: user.postDashbot:incoming 5966b36510707d49445dba71:hi
1:12:31 PM web.1 |  debug: phoenix.fetchCampaign:undefined
1:12:31 PM web.1 |  error: phoenix.fetchCampaign Not Found
1:12:31 PM web.1 |  error: dashbot response::Bad Request
```

**Comment by aaronschachter** [comment]
Yeah, I've been considering removing the default `consolebot` value and requiring the `GAMBIT_CONSOLEBOT_PHONE` config variable - because it doesn't work. If you use your phone number and your user has a `current_campaign` set in your local DB, it should work.

By default consolebot won't work with a new phone number, because we can't send a keyword to signup for a Campaign (we're posting passing `args` to our local `/chatbot`) not a `keyword`.

This brings up a few issues we're getting ready to work on in anticipation of TGM:
* Don't use rely on a `keyword` input parameter anymore, but instead inspect the incoming message to determine if it's a Campaign keyword
* Handle when a User texts into chatbot and doesn't have a `current_campaign` set ( #713 )

**Comment by rapala61** [comment]
@aaronschachter Ah ok, makes sense. Great work here! I loved the Gambit prompt 🥇. Can we make that change to require the `GAMBIT_CONSOLEBOT_PHONE` env variable instead of falling back to `consolebot`? That would be my only ask.

**Comment by aaronschachter** [comment]
Thanks! Will do! 💯

**Pull request merged**
