### PR TITLE
Update SMS Voice & Compliance/Welcome Copy

### PR DESCRIPTION
**Pull request by mendelB**
#### What's this PR do?
tell us, what have you changed?
- We've updated our compliance copy / welcome message to introduce the new cohort of SMS voices
- We've updated the official Rivescript bot `name` from `Tej` to `Ben` along with any hardcoded references

#### How should this be reviewed?
tell us, how can we review, to test that this works
Am I missing any other references? I noticed some documentation & stubs still referencing Tej, but these seemed to clearly reference historical or example messaging, so wasn't sure if it was necessary to update.

#### Any background context you want to provide?
what else?
With Tej's departure ( 😢 ), we've migrated to a cohort of SMS voices, with Ben being the de facto bot `name`. ([See Slack](https://dosomething.slack.com/archives/C03T8SDMS/p1601484313001400?thread_ts=1601415311.001100&cid=C03T8SDMS))

#### Relevant tickets
Fixes #
Fixes Pivotal [Card#175060670](https://www.pivotaltracker.com/story/show/175060670)

#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tests added/updated for new features/bug fixes.
- [ ] ENV variables added/updated for new features/bug fixes.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love.

image

### CODE REVIEW

**Comment by mendelB** [comment]
As an aside @aaronschachter, there didn't seem to be many places with a hardcoded name (aside from the two updates in the `macro.js`), so this could just be overkill -- but wondering if we could process those messages through the Rivescript templating similar to Contentful content (I'm speaking roughly because I'm not familiar with the nuances), so that instead of hardcoding a name we could use the `<bot name>` templating?

**Comment by aaronschachter** [comment]
It'd be sweet to use`<bot name>` instead of hardcoding the `Ben`, but this message text is set after we've already sent the inbound message to the Rivescript middleware (and got the macro name back, like `subscriptionStatusActive` or `subscriptionStatusLess`):
https://github.com/DoSomething/gambit/blob/a3ebe2c96c32ff8b3e42453352562ed58742d8cb/brain/macros.rive#L15-L25

It could be nice to potentially call a Rivescript function to replace any `<bot>` variables in macro text... but don't think we need to worry about it for this pass.

**Review by aaronschachter — APPROVED** [review]
> Am I missing any other references?

I don't think so!

**Comment by mendelB** [comment]
Ah thanks for that context @aaronschachter and agreed for now it certainly doesn't seem like we need to worry about this. Especially because I updated in https://github.com/DoSomething/gambit/pull/532/commits/7a109569cbc6b0f51f58fd7939f7da95eaf40abd to remove the remaining hardcoded name entirely per [Anthony in Slack](https://dosomething.slack.com/archives/C03T8SDMS/p1601490077003500?thread_ts=1601415311.001100&cid=C03T8SDMS)!

**Pull request merged**
