### PR TITLE
Hotfix/870 fix keywords wrong env 500

### LINKED ISSUE #870: Keyword for incorrect environment should return 422
_BUG_
-------------------
#### Current Behavior
```
curl -X POST \
  http://ds-mdata-responder-staging.herokuapp.com/api/v1/webhooks/gambit-chatbot-mdata \
  -H '<AUTH HEADER>' \
  -H 'content-type: application/json' \
  -d '{
  "keyword": "SHARE",
  "phone": "1<PHONE NUMBER>",
  "message_id": "841415468",
  "profile_id": "167181555"
}'
```

response_status=500 response_status_text="Internal Server Error" {"error":{"code":500,"message":"Keyword share environment error: defined as undefined but sent to thor."}}

#### Desired Behavior
response_status=422 response_status_text="422 unprocessable entity" {"error":{"code":422,"message":"Keyword share environment error: defined as undefined but sent to thor."}}

#### Why This Matters
So blink won't retry it 100 times.

### PR DESCRIPTION
**Pull request by rapala61**
#### What's this PR do?
Sends a 422 error instead of a 500 when querying the contentful API for a keyword that doesn't match the requests environment.

#### How should this be reviewed?
Use Postman locally (undefined env) to signup to a campaign by using a production KEYWORD. It should fail with a 422 error.

Example for Keyword `repeat`
```
{
  "error": {
    "code": 422,
    "message": "Keyword repeat environment error: defined as undefined but sent to thor."
  }
}
```

#### Any background context you want to provide?
It's blocking Blink. Blink will retry on any non 422 error.

#### Relevant tickets
Fixes #870

#### Checklist
- [x] Documentation added for new features/changed endpoints.
- [x] Tested Locally.
- [ ] Tested on staging.

### CODE REVIEW

**Comment by sergii-tkachenko** [comment]
Why does it contain a bunch of `	Merge branch 'release-` commits? Is it really needed?

**Comment by rapala61** [comment]
@sergii-tkachenko I think is a side effect of the github flow we use VS a hotfix which is a branch off of master. When we merge releases into boith develop and master, we do it separately, so the merge of the release into master has a different hash than the merge of the release into develop, this has a side effect of re-merging these release commits into develop when we have hotfixes.

**Comment by sergii-tkachenko** [comment]
Yes, something's definitely not right with the flow.

**Comment by sergii-tkachenko** [comment]
Works on staging. Thank you, Rafa!

**Comment by sergii-tkachenko** [comment]
And on production.

**Pull request merged**
